---
- name: Deploy MatchMyResume Application				
  hosts: webservers
  become: yes

  tasks:
    - name: Update system packages
      apt:
        update_cache: yes

    - name: Install Node.js and Git
      apt:
        name: ['nodejs', 'npm', 'git']
        state: present

    - name: Clone the MatchMyResume repository
      git:
        repo: 'https://github.com/sahilsingh12221802/MatchMy-Resume.git'
        dest: '/var/www/matchmyresume'
        version: main
        force: yes

    - name: Install Node.js dependencies
      command: npm install
      args:
        chdir: /var/www/matchmyresume
- name: Build the application
  command: npm run build
      args:
        chdir: /var/www/matchmyresume

    - name: Copy build output to Nginx web root
      ansible.builtin.shell: cp -r /var/www/matchmyresume/dist/* /var/www/html/
      args:
        chdir: /var/www/matchmyresume

    - name: Restart Nginx service
      service:
        name: nginx
        state: restarted
